### ISSUE TITLE
Yast2-vpn 

### ISSUE THREAD

**Issue by rmsickler1** [yast/yast-vpn#21]
The yast2-vpn module slowed my internet connection from 500mbps to 40mbps.

**Comment by dgdavid** [comment]
Hi @rmsickler1!

Without more data, I'd say that it is the connection is slowed down by the VPN itself, not because the YaST module. Read https://www.cnet.com/tech/services-and-software/how-to-speed-up-your-vpn-connection/ or https://nordvpn.com/blog/does-vpn-slow-down-internet/, for example.

Did you aware that?

**Comment by dgdavid** [comment]
Note: adding the "other-maintainer" label to this in order to help filtering the various list of issues since the yast2-vpn package is developed and maintained by the Samba Team at SUSE, instead of the core YaST Team.
